var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc(-1,undefined);
subject.inc(1,undefined);
subject.inc(-1,"undefinedno");
subject.inc(1,"undefinedno");
subject.weird(8,-1,41,"strict");
subject.weird(6,-1,41,"strict");
subject.weird(8,1,41,"strict");
subject.weird(6,1,41,"strict");
subject.weird(8,-1,43,"strict");
subject.weird(6,-1,43,"strict");
subject.weird(8,1,43,"strict");
subject.weird(6,1,43,"strict");
subject.weird(8,-1,41,"strictno");
subject.weird(6,-1,41,"strictno");
subject.weird(8,1,41,"strictno");
subject.weird(6,1,41,"strictno");
subject.weird(8,-1,43,"strictno");
subject.weird(6,-1,43,"strictno");
subject.weird(8,1,43,"strictno");
subject.weird(6,1,43,"strictno");
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
